spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/structure_security
    username: postgres
    password: 1113
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
server:
  port: 9999
